### ISSUE TITLE
UART output via printf does not work

### ISSUE THREAD

**Issue by AlexAldoshin** [minilogic/f1c_nonos#2]
UART output via printf does not work

Perhaps additional project settings are needed?

**Comment by minilogic** [comment]
Thish project uses UART0 on the PE0(UART0_RX) and PE1(UART0_TX) pins. Initialization is done in [boot.c](https://github.com/minilogic/f1c_nonos/blob/main/drv/boot.c#L69)

**Comment by AlexAldoshin** [comment]
> В этом проекте используется UART0 на выводах PE0(UART0_RX) и PE1(UART0_TX). Инициализация выполняется в [boot.c](https://github.com/minilogic/f1c_nonos/blob/main/drv/boot.c#L69)

Thank you!
I have a Lctech Pi F1C200s development board. In it, the UART USB converter is connected to UART1.
Direct connection to UART0 solved the problem.
